codecov:
  require_ci_to_pass: yescoverage:
  precision: 2
  round: down
  range: "70...100"status:
    project: yes
    patch: yes
    changes: noparsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: nocomment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
  
ignore:
  # Ignore coverage for generated and third party code.
  - "**/Plot_*.py"

