coverage:
  precision: 2
  round: down
  range: "65...100"

  status:
    project: no
    patch: yes
    changes: no
    
ignore:
  # Ignore coverage for generated and third party code.
  - "**/Plot_*.py"
  - "plot"
  - "tracklib/plot"
  
