name: Tracklib coverage

on:
  pull_request:
    branches: [ main ]


jobs:
  coverage:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Test with pytest
      run: |
        mkdir -p ${{ github.workspace }}/data/test
        chmod 777 -R ${{ github.workspace }}/data/test
        coverage run -m --source=tracklib/ pytest test/
        coverage xml
    
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
      
    

